name = "jockey-relay"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
C2_AUTH = "supersecret123"
BACKEND_URL = "https://jockey-framework.onrender.com"

# Bind the KV Namespace you created in the Cloudflare Dashboard
[[kv_namespaces]]
binding = "PAYLOAD_KV"
id = "71a44eca334945f9933fe2dae116a8d0"