"""initial

Revision ID: 26fa71ddd354
Revises: 
Create Date: 2026-08-28 01:17:08.308600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26fa71ddd354'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('os', sa.String(length=32), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('arch', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('agent_id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('scripts',
    sa.Column('script_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('hash_before', sa.String(length=64), nullable=True),
    sa.Column('hash_after', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('script_id')
    )
    op.create_table('results',
    sa.Column('result_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('script_id', sa.String(length=64), nullable=False),
    sa.Column('data_encrypted', sa.Text(), nullable=False),
    sa.Column('data_decrypted', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.script_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_table('deploys',
    sa.Column('deploy_id', sa.String(length=64), nullable=False),
    sa.Column('script_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('result_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['results.result_id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.script_id'], ),
    sa.PrimaryKeyConstraint('deploy_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deploys')
    op.drop_table('results')
    op.drop_table('scripts')
    op.drop_table('agents')
    # ### end Alembic commands ###
